title: Alejandro Amaro | Product & Visual Designer
description: Product & Visual Designer 
baseurl: "" 
url: "https://alejandro-is.me"
collections:
  projects:
    output: true
    permalink: /projects/:path/